export interface Skill {
  name: string;
  category: string;
}

export const ALL_SKILLS: Skill[] = [
  // Software Engineering
  { name: 'JavaScript', category: 'Software Engineering' },
  { name: 'TypeScript', category: 'Software Engineering' },
  { name: 'Python', category: 'Software Engineering' },
  { name: 'Java', category: 'Software Engineering' },
  { name: 'C++', category: 'Software Engineering' },
  { name: 'C#', category: 'Software Engineering' },
  { name: 'Go', category: 'Software Engineering' },
  { name: 'Rust', category: 'Software Engineering' },
  { name: 'Swift', category: 'Software Engineering' },
  { name: 'Kotlin', category: 'Software Engineering' },
  { name: 'PHP', category: 'Software Engineering' },
  { name: 'Ruby', category: 'Software Engineering' },
  { name: 'Scala', category: 'Software Engineering' },
  { name: 'React', category: 'Software Engineering' },
  { name: 'Next.js', category: 'Software Engineering' },
  { name: 'Vue.js', category: 'Software Engineering' },
  { name: 'Angular', category: 'Software Engineering' },
  { name: 'Node.js', category: 'Software Engineering' },
  { name: 'Express.js', category: 'Software Engineering' },
  { name: 'Django', category: 'Software Engineering' },
  { name: 'Flask', category: 'Software Engineering' },
  { name: 'FastAPI', category: 'Software Engineering' },
  { name: 'Spring Boot', category: 'Software Engineering' },
  { name: 'Laravel', category: 'Software Engineering' },
  { name: 'Ruby on Rails', category: 'Software Engineering' },
  { name: 'REST APIs', category: 'Software Engineering' },
  { name: 'GraphQL', category: 'Software Engineering' },
  { name: 'Microservices', category: 'Software Engineering' },
  { name: 'Docker', category: 'Software Engineering' },
  { name: 'Kubernetes', category: 'Software Engineering' },
  { name: 'AWS', category: 'Software Engineering' },
  { name: 'Google Cloud', category: 'Software Engineering' },
  { name: 'Azure', category: 'Software Engineering' },
  { name: 'CI/CD', category: 'Software Engineering' },
  { name: 'Git', category: 'Software Engineering' },
  { name: 'GitHub', category: 'Software Engineering' },
  { name: 'Linux', category: 'Software Engineering' },
  { name: 'Redis', category: 'Software Engineering' },
  { name: 'PostgreSQL', category: 'Software Engineering' },
  { name: 'MySQL', category: 'Software Engineering' },
  { name: 'MongoDB', category: 'Software Engineering' },
  { name: 'Firebase', category: 'Software Engineering' },
  { name: 'Supabase', category: 'Software Engineering' },
  { name: 'System Design', category: 'Software Engineering' },
  { name: 'Data Structures', category: 'Software Engineering' },
  { name: 'Algorithms', category: 'Software Engineering' },
  { name: 'Object Oriented Programming', category: 'Software Engineering' },
  { name: 'Functional Programming', category: 'Software Engineering' },
  { name: 'Test Driven Development', category: 'Software Engineering' },
  { name: 'Agile', category: 'Software Engineering' },
  { name: 'Scrum', category: 'Software Engineering' },
  { name: 'DevOps', category: 'Software Engineering' },
  { name: 'Terraform', category: 'Software Engineering' },
  { name: 'Jenkins', category: 'Software Engineering' },
  { name: 'Selenium', category: 'Software Engineering' },
  { name: 'Jest', category: 'Software Engineering' },
  { name: 'Webpack', category: 'Software Engineering' },
  { name: 'Tailwind CSS', category: 'Software Engineering' },
  { name: 'HTML', category: 'Software Engineering' },
  { name: 'CSS', category: 'Software Engineering' },
  { name: 'WebSockets', category: 'Software Engineering' },
  { name: 'OAuth', category: 'Software Engineering' },
  { name: 'Blockchain', category: 'Software Engineering' },
  { name: 'Solidity', category: 'Software Engineering' },
  { name: 'Android Development', category: 'Software Engineering' },
  { name: 'iOS Development', category: 'Software Engineering' },
  { name: 'React Native', category: 'Software Engineering' },
  { name: 'Flutter', category: 'Software Engineering' },
  { name: 'Unity', category: 'Software Engineering' },
  { name: 'Embedded Systems', category: 'Software Engineering' },
  { name: 'IoT', category: 'Software Engineering' },

  // Data and AI
  { name: 'Machine Learning', category: 'Data and AI' },
  { name: 'Deep Learning', category: 'Data and AI' },
  { name: 'Artificial Intelligence', category: 'Data and AI' },
  { name: 'Natural Language Processing', category: 'Data and AI' },
  { name: 'Computer Vision', category: 'Data and AI' },
  { name: 'Data Science', category: 'Data and AI' },
  { name: 'Data Analysis', category: 'Data and AI' },
  { name: 'Data Engineering', category: 'Data and AI' },
  { name: 'Data Visualization', category: 'Data and AI' },
  { name: 'TensorFlow', category: 'Data and AI' },
  { name: 'PyTorch', category: 'Data and AI' },
  { name: 'Scikit-learn', category: 'Data and AI' },
  { name: 'Pandas', category: 'Data and AI' },
  { name: 'NumPy', category: 'Data and AI' },
  { name: 'Jupyter Notebook', category: 'Data and AI' },
  { name: 'Apache Spark', category: 'Data and AI' },
  { name: 'Hadoop', category: 'Data and AI' },
  { name: 'Tableau', category: 'Data and AI' },
  { name: 'Power BI', category: 'Data and AI' },
  { name: 'SQL', category: 'Data and AI' },
  { name: 'BigQuery', category: 'Data and AI' },
  { name: 'Snowflake', category: 'Data and AI' },
  { name: 'dbt', category: 'Data and AI' },
  { name: 'Airflow', category: 'Data and AI' },
  { name: 'MLflow', category: 'Data and AI' },
  { name: 'Feature Engineering', category: 'Data and AI' },
  { name: 'Statistical Analysis', category: 'Data and AI' },
  { name: 'A/B Testing', category: 'Data and AI' },
  { name: 'Regression Analysis', category: 'Data and AI' },
  { name: 'Time Series Analysis', category: 'Data and AI' },
  { name: 'Generative AI', category: 'Data and AI' },
  { name: 'Prompt Engineering', category: 'Data and AI' },
  { name: 'LLMs', category: 'Data and AI' },
  { name: 'RAG', category: 'Data and AI' },
  { name: 'Vector Databases', category: 'Data and AI' },
  { name: 'ETL Pipelines', category: 'Data and AI' },
  { name: 'Business Intelligence', category: 'Data and AI' },
  { name: 'Looker', category: 'Data and AI' },
  { name: 'Excel Advanced', category: 'Data and AI' },
  { name: 'Google Analytics', category: 'Data and AI' },

  // Product Management
  { name: 'Product Management', category: 'Product Management' },
  { name: 'Product Strategy', category: 'Product Management' },
  { name: 'Roadmap Planning', category: 'Product Management' },
  { name: 'User Research', category: 'Product Management' },
  { name: 'Market Research', category: 'Product Management' },
  { name: 'Competitive Analysis', category: 'Product Management' },
  { name: 'Product Analytics', category: 'Product Management' },
  { name: 'Wireframing', category: 'Product Management' },
  { name: 'Prototyping', category: 'Product Management' },
  { name: 'User Stories', category: 'Product Management' },
  { name: 'Sprint Planning', category: 'Product Management' },
  { name: 'Stakeholder Management', category: 'Product Management' },
  { name: 'Go to Market Strategy', category: 'Product Management' },
  { name: 'Pricing Strategy', category: 'Product Management' },
  { name: 'OKRs', category: 'Product Management' },
  { name: 'KPI Tracking', category: 'Product Management' },
  { name: 'JIRA', category: 'Product Management' },
  { name: 'Confluence', category: 'Product Management' },
  { name: 'Notion', category: 'Product Management' },
  { name: 'Figma', category: 'Product Management' },
  { name: 'Miro', category: 'Product Management' },
  { name: 'Amplitude', category: 'Product Management' },
  { name: 'Mixpanel', category: 'Product Management' },
  { name: 'Customer Journey Mapping', category: 'Product Management' },
  { name: 'Feature Prioritization', category: 'Product Management' },

  // Design
  { name: 'UI Design', category: 'Design' },
  { name: 'UX Design', category: 'Design' },
  { name: 'Visual Design', category: 'Design' },
  { name: 'Interaction Design', category: 'Design' },
  { name: 'Motion Design', category: 'Design' },
  { name: 'Brand Identity', category: 'Design' },
  { name: 'Typography', category: 'Design' },
  { name: 'Color Theory', category: 'Design' },
  { name: 'Adobe Photoshop', category: 'Design' },
  { name: 'Adobe Illustrator', category: 'Design' },
  { name: 'Adobe XD', category: 'Design' },
  { name: 'Adobe InDesign', category: 'Design' },
  { name: 'Adobe After Effects', category: 'Design' },
  { name: 'Adobe Premiere Pro', category: 'Design' },
  { name: 'Figma', category: 'Design' },
  { name: 'Sketch', category: 'Design' },
  { name: 'Canva', category: 'Design' },
  { name: 'Blender', category: 'Design' },
  { name: '3D Modeling', category: 'Design' },
  { name: 'Illustration', category: 'Design' },
  { name: 'Design Systems', category: 'Design' },
  { name: 'Usability Testing', category: 'Design' },
  { name: 'Information Architecture', category: 'Design' },
  { name: 'Accessibility Design', category: 'Design' },
  { name: 'Design Thinking', category: 'Design' },
  { name: 'Video Editing', category: 'Design' },
  { name: 'Photography', category: 'Design' },
  { name: 'Content Creation', category: 'Design' },

  // Marketing
  { name: 'Digital Marketing', category: 'Marketing' },
  { name: 'Content Marketing', category: 'Marketing' },
  { name: 'SEO', category: 'Marketing' },
  { name: 'SEM', category: 'Marketing' },
  { name: 'Social Media Marketing', category: 'Marketing' },
  { name: 'Email Marketing', category: 'Marketing' },
  { name: 'Performance Marketing', category: 'Marketing' },
  { name: 'Growth Hacking', category: 'Marketing' },
  { name: 'Brand Management', category: 'Marketing' },
  { name: 'Copywriting', category: 'Marketing' },
  { name: 'Content Writing', category: 'Marketing' },
  { name: 'Influencer Marketing', category: 'Marketing' },
  { name: 'Affiliate Marketing', category: 'Marketing' },
  { name: 'Google Ads', category: 'Marketing' },
  { name: 'Facebook Ads', category: 'Marketing' },
  { name: 'Instagram Marketing', category: 'Marketing' },
  { name: 'LinkedIn Marketing', category: 'Marketing' },
  { name: 'YouTube Marketing', category: 'Marketing' },
  { name: 'Marketing Automation', category: 'Marketing' },
  { name: 'HubSpot', category: 'Marketing' },
  { name: 'Salesforce', category: 'Marketing' },
  { name: 'Mailchimp', category: 'Marketing' },
  { name: 'Conversion Rate Optimization', category: 'Marketing' },
  { name: 'Funnel Optimization', category: 'Marketing' },
  { name: 'Market Segmentation', category: 'Marketing' },
  { name: 'Customer Acquisition', category: 'Marketing' },
  { name: 'Retention Marketing', category: 'Marketing' },
  { name: 'PR and Communications', category: 'Marketing' },
  { name: 'Event Marketing', category: 'Marketing' },
  { name: 'Podcast Marketing', category: 'Marketing' },

  // Finance and Banking
  { name: 'Financial Analysis', category: 'Finance' },
  { name: 'Financial Modeling', category: 'Finance' },
  { name: 'Valuation', category: 'Finance' },
  { name: 'Investment Banking', category: 'Finance' },
  { name: 'Equity Research', category: 'Finance' },
  { name: 'Portfolio Management', category: 'Finance' },
  { name: 'Risk Management', category: 'Finance' },
  { name: 'Credit Analysis', category: 'Finance' },
  { name: 'Corporate Finance', category: 'Finance' },
  { name: 'Accounting', category: 'Finance' },
  { name: 'Taxation', category: 'Finance' },
  { name: 'GST', category: 'Finance' },
  { name: 'Income Tax', category: 'Finance' },
  { name: 'Tally ERP', category: 'Finance' },
  { name: 'SAP FICO', category: 'Finance' },
  { name: 'QuickBooks', category: 'Finance' },
  { name: 'Zoho Books', category: 'Finance' },
  { name: 'Auditing', category: 'Finance' },
  { name: 'Compliance', category: 'Finance' },
  { name: 'CA', category: 'Finance' },
  { name: 'CFA', category: 'Finance' },
  { name: 'FRM', category: 'Finance' },
  { name: 'SEBI Regulations', category: 'Finance' },
  { name: 'RBI Guidelines', category: 'Finance' },
  { name: 'Banking Operations', category: 'Finance' },
  { name: 'Trade Finance', category: 'Finance' },
  { name: 'Treasury Management', category: 'Finance' },
  { name: 'Derivatives', category: 'Finance' },
  { name: 'Mutual Funds', category: 'Finance' },
  { name: 'Insurance', category: 'Finance' },
  { name: 'Microfinance', category: 'Finance' },
  { name: 'Excel Financial Modeling', category: 'Finance' },

  // Healthcare
  { name: 'Clinical Research', category: 'Healthcare' },
  { name: 'Patient Care', category: 'Healthcare' },
  { name: 'Medical Coding', category: 'Healthcare' },
  { name: 'Pharmacovigilance', category: 'Healthcare' },
  { name: 'Regulatory Affairs', category: 'Healthcare' },
  { name: 'Quality Assurance', category: 'Healthcare' },
  { name: 'GCP Guidelines', category: 'Healthcare' },
  { name: 'ICH Guidelines', category: 'Healthcare' },
  { name: 'Medical Writing', category: 'Healthcare' },
  { name: 'Healthcare Analytics', category: 'Healthcare' },
  { name: 'Hospital Management', category: 'Healthcare' },
  { name: 'Public Health', category: 'Healthcare' },
  { name: 'Epidemiology', category: 'Healthcare' },
  { name: 'Biostatistics', category: 'Healthcare' },
  { name: 'Nursing', category: 'Healthcare' },
  { name: 'Physiotherapy', category: 'Healthcare' },
  { name: 'Radiology', category: 'Healthcare' },
  { name: 'Pathology', category: 'Healthcare' },
  { name: 'Telemedicine', category: 'Healthcare' },
  { name: 'EMR Systems', category: 'Healthcare' },
  { name: 'NABH Standards', category: 'Healthcare' },
  { name: 'Pharma Sales', category: 'Healthcare' },
  { name: 'Drug Regulatory Affairs', category: 'Healthcare' },
  { name: 'Medical Devices', category: 'Healthcare' },
  { name: 'Biotechnology', category: 'Healthcare' },

  // Operations and Management
  { name: 'Project Management', category: 'Operations' },
  { name: 'Operations Management', category: 'Operations' },
  { name: 'Supply Chain Management', category: 'Operations' },
  { name: 'Logistics', category: 'Operations' },
  { name: 'Inventory Management', category: 'Operations' },
  { name: 'Procurement', category: 'Operations' },
  { name: 'Vendor Management', category: 'Operations' },
  { name: 'Quality Management', category: 'Operations' },
  { name: 'Six Sigma', category: 'Operations' },
  { name: 'Lean Management', category: 'Operations' },
  { name: 'PMP', category: 'Operations' },
  { name: 'Prince2', category: 'Operations' },
  { name: 'Business Analysis', category: 'Operations' },
  { name: 'Process Improvement', category: 'Operations' },
  { name: 'Change Management', category: 'Operations' },
  { name: 'Strategic Planning', category: 'Operations' },
  { name: 'P&L Management', category: 'Operations' },
  { name: 'Budget Management', category: 'Operations' },
  { name: 'CRM', category: 'Operations' },
  { name: 'ERP Systems', category: 'Operations' },
  { name: 'SAP', category: 'Operations' },
  { name: 'Oracle', category: 'Operations' },
  { name: 'Warehouse Management', category: 'Operations' },
  { name: 'Fleet Management', category: 'Operations' },
  { name: 'Facility Management', category: 'Operations' },

  // Human Resources
  { name: 'Talent Acquisition', category: 'Human Resources' },
  { name: 'Recruitment', category: 'Human Resources' },
  { name: 'HR Operations', category: 'Human Resources' },
  { name: 'Payroll Management', category: 'Human Resources' },
  { name: 'Performance Management', category: 'Human Resources' },
  { name: 'Learning and Development', category: 'Human Resources' },
  { name: 'Employee Engagement', category: 'Human Resources' },
  { name: 'HRIS', category: 'Human Resources' },
  { name: 'Labour Law', category: 'Human Resources' },
  { name: 'Compensation and Benefits', category: 'Human Resources' },
  { name: 'Organizational Development', category: 'Human Resources' },
  { name: 'Diversity and Inclusion', category: 'Human Resources' },
  { name: 'Employer Branding', category: 'Human Resources' },
  { name: 'HR Analytics', category: 'Human Resources' },
  { name: 'Onboarding', category: 'Human Resources' },
  { name: 'Workforce Planning', category: 'Human Resources' },
  { name: 'Succession Planning', category: 'Human Resources' },
  { name: 'Industrial Relations', category: 'Human Resources' },
  { name: 'Statutory Compliance', category: 'Human Resources' },
  { name: 'Greythr', category: 'Human Resources' },
  { name: 'Darwinbox', category: 'Human Resources' },
  { name: 'LinkedIn Recruiter', category: 'Human Resources' },

  // Sales
  { name: 'B2B Sales', category: 'Sales' },
  { name: 'B2C Sales', category: 'Sales' },
  { name: 'Inside Sales', category: 'Sales' },
  { name: 'Field Sales', category: 'Sales' },
  { name: 'Enterprise Sales', category: 'Sales' },
  { name: 'SaaS Sales', category: 'Sales' },
  { name: 'Channel Sales', category: 'Sales' },
  { name: 'Key Account Management', category: 'Sales' },
  { name: 'Business Development', category: 'Sales' },
  { name: 'Lead Generation', category: 'Sales' },
  { name: 'Cold Calling', category: 'Sales' },
  { name: 'Sales Forecasting', category: 'Sales' },
  { name: 'CRM Tools', category: 'Sales' },
  { name: 'Zoho CRM', category: 'Sales' },
  { name: 'Salesforce CRM', category: 'Sales' },
  { name: 'Negotiation', category: 'Sales' },
  { name: 'Closing Deals', category: 'Sales' },
  { name: 'Retail Sales', category: 'Sales' },
  { name: 'Revenue Generation', category: 'Sales' },
  { name: 'Territory Management', category: 'Sales' },

  // Legal
  { name: 'Corporate Law', category: 'Legal' },
  { name: 'Contract Drafting', category: 'Legal' },
  { name: 'Legal Research', category: 'Legal' },
  { name: 'Litigation', category: 'Legal' },
  { name: 'Intellectual Property', category: 'Legal' },
  { name: 'Mergers and Acquisitions', category: 'Legal' },
  { name: 'Compliance Management', category: 'Legal' },
  { name: 'GDPR', category: 'Legal' },
  { name: 'Due Diligence', category: 'Legal' },
  { name: 'Companies Act', category: 'Legal' },
  { name: 'SEBI Regulations', category: 'Legal' },
  { name: 'Arbitration', category: 'Legal' },
  { name: 'Legal Documentation', category: 'Legal' },

  // Education
  { name: 'Teaching', category: 'Education' },
  { name: 'Curriculum Development', category: 'Education' },
  { name: 'E-learning', category: 'Education' },
  { name: 'Instructional Design', category: 'Education' },
  { name: 'Training and Development', category: 'Education' },
  { name: 'Academic Research', category: 'Education' },
  { name: 'EdTech', category: 'Education' },
  { name: 'Student Counseling', category: 'Education' },
  { name: 'Special Education', category: 'Education' },
  { name: 'CBSE Curriculum', category: 'Education' },
  { name: 'IB Curriculum', category: 'Education' },

  // Civil and Mechanical Engineering
  { name: 'AutoCAD', category: 'Engineering' },
  { name: 'SolidWorks', category: 'Engineering' },
  { name: 'CATIA', category: 'Engineering' },
  { name: 'ANSYS', category: 'Engineering' },
  { name: 'Revit', category: 'Engineering' },
  { name: 'Civil 3D', category: 'Engineering' },
  { name: 'Structural Analysis', category: 'Engineering' },
  { name: 'Project Engineering', category: 'Engineering' },
  { name: 'Site Management', category: 'Engineering' },
  { name: 'Quantity Surveying', category: 'Engineering' },
  { name: 'Electrical Engineering', category: 'Engineering' },
  { name: 'Mechanical Design', category: 'Engineering' },
  { name: 'Manufacturing', category: 'Engineering' },
  { name: 'Quality Control', category: 'Engineering' },
  { name: 'HVAC', category: 'Engineering' },
  { name: 'PLC Programming', category: 'Engineering' },
  { name: 'SCADA', category: 'Engineering' },
  { name: 'BIM', category: 'Engineering' },
  { name: 'GIS', category: 'Engineering' },
  { name: 'Environmental Engineering', category: 'Engineering' },

  // Soft Skills
  { name: 'Leadership', category: 'Soft Skills' },
  { name: 'Communication', category: 'Soft Skills' },
  { name: 'Problem Solving', category: 'Soft Skills' },
  { name: 'Critical Thinking', category: 'Soft Skills' },
  { name: 'Team Management', category: 'Soft Skills' },
  { name: 'Collaboration', category: 'Soft Skills' },
  { name: 'Time Management', category: 'Soft Skills' },
  { name: 'Adaptability', category: 'Soft Skills' },
  { name: 'Creativity', category: 'Soft Skills' },
  { name: 'Emotional Intelligence', category: 'Soft Skills' },
  { name: 'Conflict Resolution', category: 'Soft Skills' },
  { name: 'Decision Making', category: 'Soft Skills' },
  { name: 'Presentation Skills', category: 'Soft Skills' },
  { name: 'Public Speaking', category: 'Soft Skills' },
  { name: 'Mentoring', category: 'Soft Skills' },
  { name: 'Coaching', category: 'Soft Skills' },
  { name: 'Networking', category: 'Soft Skills' },
  { name: 'Customer Service', category: 'Soft Skills' },
  { name: 'Attention to Detail', category: 'Soft Skills' },
  { name: 'Self Motivation', category: 'Soft Skills' },
  { name: 'Work Ethic', category: 'Soft Skills' },
  { name: 'Cultural Awareness', category: 'Soft Skills' },
  { name: 'Empathy', category: 'Soft Skills' },
  { name: 'Resilience', category: 'Soft Skills' },
  { name: 'Analytical Thinking', category: 'Soft Skills' },
  { name: 'Strategic Thinking', category: 'Soft Skills' },
  { name: 'Multitasking', category: 'Soft Skills' },
  { name: 'Initiative', category: 'Soft Skills' },
  { name: 'Accountability', category: 'Soft Skills' },
  { name: 'Integrity', category: 'Soft Skills' },

  // Languages
  { name: 'English', category: 'Languages' },
  { name: 'Hindi', category: 'Languages' },
  { name: 'Telugu', category: 'Languages' },
  { name: 'Tamil', category: 'Languages' },
  { name: 'Kannada', category: 'Languages' },
  { name: 'Malayalam', category: 'Languages' },
  { name: 'Marathi', category: 'Languages' },
  { name: 'Bengali', category: 'Languages' },
  { name: 'Gujarati', category: 'Languages' },
  { name: 'Punjabi', category: 'Languages' },
  { name: 'French', category: 'Languages' },
  { name: 'German', category: 'Languages' },
  { name: 'Spanish', category: 'Languages' },
  { name: 'Mandarin', category: 'Languages' },
  { name: 'Japanese', category: 'Languages' },
  { name: 'Arabic', category: 'Languages' },

  // Cybersecurity
  { name: 'Cybersecurity', category: 'Cybersecurity' },
  { name: 'Network Security', category: 'Cybersecurity' },
  { name: 'Ethical Hacking', category: 'Cybersecurity' },
  { name: 'Penetration Testing', category: 'Cybersecurity' },
  { name: 'SIEM', category: 'Cybersecurity' },
  { name: 'SOC Operations', category: 'Cybersecurity' },
  { name: 'Vulnerability Assessment', category: 'Cybersecurity' },
  { name: 'ISO 27001', category: 'Cybersecurity' },
  { name: 'VAPT', category: 'Cybersecurity' },
  { name: 'Cloud Security', category: 'Cybersecurity' },
  { name: 'Identity Management', category: 'Cybersecurity' },
  { name: 'Incident Response', category: 'Cybersecurity' },
  { name: 'Forensics', category: 'Cybersecurity' },
  { name: 'Firewall Management', category: 'Cybersecurity' },

  // Indian specific tools and skills
  { name: 'Tally Prime', category: 'Indian Tools' },
  { name: 'Busy Accounting', category: 'Indian Tools' },
  { name: 'Zerodha API', category: 'Indian Tools' },
  { name: 'DigiLocker Integration', category: 'Indian Tools' },
  { name: 'UPI Integration', category: 'Indian Tools' },
  { name: 'Razorpay', category: 'Indian Tools' },
  { name: 'Cashfree', category: 'Indian Tools' },
  { name: 'IRCTC API', category: 'Indian Tools' },
  { name: 'Aadhaar API', category: 'Indian Tools' },
  { name: 'GST Portal', category: 'Indian Tools' },
  { name: 'MCA Portal', category: 'Indian Tools' },
  { name: 'IndiaMart', category: 'Indian Tools' },
  { name: 'TradeIndia', category: 'Indian Tools' },
  { name: 'Naukri Portal', category: 'Indian Tools' },
  { name: 'Internshala', category: 'Indian Tools' },

  // Research and Academia
  { name: 'Research Methodology', category: 'Research' },
  { name: 'Academic Writing', category: 'Research' },
  { name: 'Literature Review', category: 'Research' },
  { name: 'SPSS', category: 'Research' },
  { name: 'MATLAB', category: 'Research' },
  { name: 'R Programming', category: 'Research' },
  { name: 'Qualitative Research', category: 'Research' },
  { name: 'Quantitative Research', category: 'Research' },
  { name: 'Survey Design', category: 'Research' },
  { name: 'Grant Writing', category: 'Research' },
  { name: 'Patent Writing', category: 'Research' },
  { name: 'Publications', category: 'Research' },

  // Consulting
  { name: 'Management Consulting', category: 'Consulting' },
  { name: 'Strategy Consulting', category: 'Consulting' },
  { name: 'IT Consulting', category: 'Consulting' },
  { name: 'Financial Consulting', category: 'Consulting' },
  { name: 'HR Consulting', category: 'Consulting' },
  { name: 'Client Management', category: 'Consulting' },
  { name: 'Proposal Writing', category: 'Consulting' },
  { name: 'Presentation Decks', category: 'Consulting' },
  { name: 'Workshop Facilitation', category: 'Consulting' },
  { name: 'McKinsey Framework', category: 'Consulting' },
  { name: 'SWOT Analysis', category: 'Consulting' },
  { name: 'Business Case Development', category: 'Consulting' },
];

// Job roles with required skills for match scoring
export const JOB_ROLES = [
  {
    id: 'software_engineer',
    title: 'Software Engineer',
    icon: '💻',
    requiredSkills: ['JavaScript', 'Python', 'Java', 'Data Structures', 'Algorithms', 'Git', 'REST APIs', 'SQL'],
    niceToHave: ['Docker', 'AWS', 'System Design', 'Agile'],
  },
  {
    id: 'frontend_developer',
    title: 'Frontend Developer',
    icon: '🎨',
    requiredSkills: ['JavaScript', 'TypeScript', 'React', 'HTML', 'CSS', 'Git'],
    niceToHave: ['Next.js', 'Tailwind CSS', 'Figma', 'Performance Optimization'],
  },
  {
    id: 'backend_developer',
    title: 'Backend Developer',
    icon: '⚙️',
    requiredSkills: ['Python', 'Node.js', 'SQL', 'REST APIs', 'Docker', 'Git'],
    niceToHave: ['Kubernetes', 'AWS', 'Redis', 'System Design'],
  },
  {
    id: 'data_scientist',
    title: 'Data Scientist',
    icon: '📊',
    requiredSkills: ['Python', 'Machine Learning', 'SQL', 'Statistical Analysis', 'Pandas', 'NumPy'],
    niceToHave: ['TensorFlow', 'Deep Learning', 'Tableau', 'Big Data'],
  },
  {
    id: 'data_analyst',
    title: 'Data Analyst',
    icon: '📈',
    requiredSkills: ['SQL', 'Excel Advanced', 'Data Analysis', 'Data Visualization', 'Python'],
    niceToHave: ['Tableau', 'Power BI', 'A/B Testing', 'Google Analytics'],
  },
  {
    id: 'product_manager',
    title: 'Product Manager',
    icon: '🎯',
    requiredSkills: ['Product Management', 'User Research', 'Roadmap Planning', 'Stakeholder Management', 'Data Analysis'],
    niceToHave: ['Figma', 'SQL', 'Agile', 'Go to Market Strategy'],
  },
  {
    id: 'ui_ux_designer',
    title: 'UI/UX Designer',
    icon: '✏️',
    requiredSkills: ['UI Design', 'UX Design', 'Figma', 'Prototyping', 'User Research'],
    niceToHave: ['Motion Design', 'Design Systems', 'Adobe XD', 'Usability Testing'],
  },
  {
    id: 'digital_marketer',
    title: 'Digital Marketer',
    icon: '📢',
    requiredSkills: ['Digital Marketing', 'SEO', 'Social Media Marketing', 'Google Analytics', 'Content Marketing'],
    niceToHave: ['Google Ads', 'Facebook Ads', 'Email Marketing', 'HubSpot'],
  },
  {
    id: 'devops_engineer',
    title: 'DevOps Engineer',
    icon: '🔧',
    requiredSkills: ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux', 'Git'],
    niceToHave: ['Terraform', 'Jenkins', 'Python', 'Cloud Security'],
  },
  {
    id: 'ml_engineer',
    title: 'ML Engineer',
    icon: '🤖',
    requiredSkills: ['Machine Learning', 'Python', 'TensorFlow', 'Deep Learning', 'SQL', 'Feature Engineering'],
    niceToHave: ['MLflow', 'Kubernetes', 'Spark', 'LLMs'],
  },
  {
    id: 'business_analyst',
    title: 'Business Analyst',
    icon: '📋',
    requiredSkills: ['Business Analysis', 'SQL', 'Data Analysis', 'Stakeholder Management', 'Process Improvement'],
    niceToHave: ['Power BI', 'JIRA', 'Agile', 'Excel Advanced'],
  },
  {
    id: 'financial_analyst',
    title: 'Financial Analyst',
    icon: '💰',
    requiredSkills: ['Financial Analysis', 'Financial Modeling', 'Excel Advanced', 'Accounting', 'SQL'],
    niceToHave: ['Tableau', 'Power BI', 'Valuation', 'CFA'],
  },
  {
    id: 'hr_manager',
    title: 'HR Manager',
    icon: '👥',
    requiredSkills: ['Talent Acquisition', 'HR Operations', 'Performance Management', 'Labour Law', 'Payroll Management'],
    niceToHave: ['HR Analytics', 'HRIS', 'Employee Engagement', 'Learning and Development'],
  },
  {
    id: 'sales_manager',
    title: 'Sales Manager',
    icon: '🤝',
    requiredSkills: ['B2B Sales', 'Key Account Management', 'CRM Tools', 'Lead Generation', 'Negotiation'],
    niceToHave: ['Sales Forecasting', 'Business Development', 'Salesforce CRM', 'Revenue Generation'],
  },
  {
    id: 'content_writer',
    title: 'Content Writer',
    icon: '✍️',
    requiredSkills: ['Content Writing', 'SEO', 'Copywriting', 'Research Methodology', 'English'],
    niceToHave: ['Social Media Marketing', 'WordPress', 'Content Marketing', 'Email Marketing'],
  },
  {
    id: 'cybersecurity_analyst',
    title: 'Cybersecurity Analyst',
    icon: '🔐',
    requiredSkills: ['Cybersecurity', 'Network Security', 'Vulnerability Assessment', 'SIEM', 'Incident Response'],
    niceToHave: ['Ethical Hacking', 'Cloud Security', 'ISO 27001', 'Penetration Testing'],
  },
  {
    id: 'project_manager',
    title: 'Project Manager',
    icon: '📌',
    requiredSkills: ['Project Management', 'Stakeholder Management', 'Risk Management', 'Agile', 'Budget Management'],
    niceToHave: ['PMP', 'JIRA', 'Scrum', 'Change Management'],
  },
  {
    id: 'ca_accountant',
    title: 'CA / Accountant',
    icon: '🧾',
    requiredSkills: ['CA', 'Accounting', 'Taxation', 'GST', 'Tally ERP', 'Auditing'],
    niceToHave: ['SAP FICO', 'Financial Modeling', 'Compliance', 'Income Tax'],
  },
];

// Function to calculate match score
export function calculateMatchScore(userSkills: string[], jobRole: typeof JOB_ROLES[0]): number {
  const userSkillsLower = userSkills.map(s => s.toLowerCase());
  const requiredMatches = jobRole.requiredSkills.filter(s =>
    userSkillsLower.includes(s.toLowerCase())
  ).length;
  const niceMatches = jobRole.niceToHave.filter(s =>
    userSkillsLower.includes(s.toLowerCase())
  ).length;

  const requiredScore = (requiredMatches / jobRole.requiredSkills.length) * 70;
  const niceScore = (niceMatches / jobRole.niceToHave.length) * 30;

  return Math.round(requiredScore + niceScore);
}

// Function to get skill suggestions
export function getSkillSuggestions(query: string, limit = 8): Skill[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return ALL_SKILLS.filter(s =>
    s.name.toLowerCase().includes(q)
  ).slice(0, limit);
}

// Get top matching jobs for user skills
export function getTopJobMatches(userSkills: string[], limit = 5) {
  return JOB_ROLES
    .map(role => ({
      ...role,
      score: calculateMatchScore(userSkills, role),
      missingSkills: role.requiredSkills.filter(s =>
        !userSkills.map(u => u.toLowerCase()).includes(s.toLowerCase())
      ),
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limit);
}